
package wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "primeServiceService", targetNamespace = "http://wsserver/", wsdlLocation = "http://localhost:1212/prim?wsdl")
public class PrimeServiceService
    extends Service
{

    private final static URL PRIMESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRIMESERVICESERVICE_EXCEPTION;
    private final static QName PRIMESERVICESERVICE_QNAME = new QName("http://wsserver/", "primeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1212/prim?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRIMESERVICESERVICE_WSDL_LOCATION = url;
        PRIMESERVICESERVICE_EXCEPTION = e;
    }

    public PrimeServiceService() {
        super(__getWsdlLocation(), PRIMESERVICESERVICE_QNAME);
    }

    public PrimeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRIMESERVICESERVICE_QNAME, features);
    }

    public PrimeServiceService(URL wsdlLocation) {
        super(wsdlLocation, PRIMESERVICESERVICE_QNAME);
    }

    public PrimeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRIMESERVICESERVICE_QNAME, features);
    }

    public PrimeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrimeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrimeService
     */
    @WebEndpoint(name = "primeServicePort")
    public PrimeService getPrimeServicePort() {
        return super.getPort(new QName("http://wsserver/", "primeServicePort"), PrimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrimeService
     */
    @WebEndpoint(name = "primeServicePort")
    public PrimeService getPrimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsserver/", "primeServicePort"), PrimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRIMESERVICESERVICE_EXCEPTION!= null) {
            throw PRIMESERVICESERVICE_EXCEPTION;
        }
        return PRIMESERVICESERVICE_WSDL_LOCATION;
    }

}
